### ISSUE TITLE
module 'imgaug.augmenters' has no attribute 'collections'

### ISSUE THREAD

**Issue by Alymostafa** [aleju/imgaug#652]
```
import imgaug.augmenters as iaa
aug_linear = iaa.RandAugmen(m=(0, 9))
```
it gives me Error (no attribute).
try to import that
```
import imgaug.augmenters.collections as iaa

``` 
also gives me error

**Comment by aleju** [comment]
```python
import imgaug.augmenters as iaa
aug_linear = iaa.RandAugmen(m=(0, 9))
```
that should fail as the class is called `RandAugment`, not `RandAugmen`.

```python
import imgaug.augmenters.collections as iaa
```
that should work in 0.4.0. You might want to print the imgaug version: `import imgaug; print imgaug.__version__` to make sure that the right one is installed.
